
# tap repositories and their packages

tap homebrew/core
brew aom
brew apr
brew apr-util
brew aria2
brew arpack
brew assimp
brew autoconf
brew automake
brew bdw-gc
brew black
brew blahtexml
brew brotli
brew c-ares
brew c-blosc
brew ca-certificates
brew cabextract
brew cairo
brew cask
brew cdrtools
brew cjson
brew clamav
brew cmake
brew cmocka
brew compface
brew coreutils
brew curl
brew dav1d
brew dbus
brew docbook
brew docbook-xsl
brew double-conversion
brew eigen
brew epstool
brew ffmpeg
brew ffmpeg@4
brew fftw
brew fig2dev
brew flac
brew flake8
brew fltk
brew fluid-synth
brew fontconfig
brew freetds
brew freetype
brew frei0r
brew fribidi
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew gflags
brew ghostscript
brew giflib
brew gl2ps
brew glib
brew glpk
brew gmime
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnupg
brew gnuplot
brew gnutls
brew gobject-introspection
brew gpgme
brew graphicsmagick
brew graphite2
brew graphviz
brew gts
brew guile
brew harfbuzz
brew hdf5
brew hunspell
brew hwloc
brew icu4c
brew imagemagick
brew imath
brew isl
brew jansson
brew jasper
brew jbig2dec
brew jemalloc
brew jpeg
brew jpeg-turbo
brew jpeg-xl
brew json-c
brew krb5
brew lame
brew leptonica
brew libaec
brew libarchive
brew libass
brew libassuan
brew libavif
brew libb2
brew libbluray
brew libcerf
brew libde265
brew libdeflate
brew libev
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libheif
brew libiconv
brew libidn
brew libidn2
brew libksba
brew liblqr
brew libmagic
brew libmng
brew libmpc
brew libnghttp2
brew libogg
brew libomp
brew libpng
brew libpthread-stubs
brew libraw
brew librist
brew librsvg
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh
brew libssh2
brew libtasn1
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew little-cms2
brew llvm@11
brew lmdb
brew lua
brew lz4
brew lzo
brew m4
brew mas
brew mbedtls
brew md4c
brew mecab
brew mecab-ipadic
brew meson
brew metis
brew mpdecimal
brew mpfr
brew mypy
brew nasm
brew ncurses
brew neomutt
brew netpbm
brew nettle
brew nghttp2
brew ninja
brew nkf
brew nmap
brew nodebrew
brew notmuch
brew npth
brew nspr
brew nss
brew octave
brew oniguruma
brew open-jtalk
brew open-mpi
brew openblas
brew opencore-amr
brew openexr
brew openjdk
brew openjpeg
brew openldap
brew openssl@1.1
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew pinentry
brew pinentry-mac
brew pinfo
brew pixman
brew pkg-config
brew plotutils
brew portaudio
brew protobuf
brew protobuf-c
brew pstoedit
brew pyenv
brew pyqt@5
brew python@3.10
brew python@3.9
brew qdbm
brew qhull
brew qrupdate
brew qscintilla2
brew qt
brew qt@5
brew rav1e
brew readline
brew reattach-to-user-namespace
brew ripgrep
brew rocksdb
brew rtmpdump
brew rubberband
brew rust
brew samba
brew scons
brew scrcpy
brew sdl2
brew shared-mime-info
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew subversion
brew suite-sparse
brew sundials
brew swig
brew talloc
brew tcl-tk
brew tesseract
brew texinfo
brew theora
brew tokyo-cabinet
brew tree
brew unbound
brew unixodbc
brew usbredir
brew utf8proc
brew util-macros
brew w3m
brew webp
brew wget
brew wimlib
brew x264
brew x265
brew xapian
brew xerces-c
brew xmlto
brew xorgproto
brew xtrans
brew xvid
brew xz
brew yara
brew zeromq
brew zimg
brew zstd

tap homebrew/cask-versions
cask brave-browser-beta
cask discord-ptb

tap homebrew/cask
cask alfred
cask appcleaner
cask background-music
cask betterdiscord-installer
cask dozer
cask dropbox
cask gimp
cask google-chrome
cask gpg-suite
cask hammerspoon
cask julia
cask krisp
cask macfuse
cask mactex
cask mamp
cask memory-cleaner
cask nordvpn
cask obs
cask obs-virtualcam
cask onyx
cask slack
cask supercollider
cask texstudio
cask utm
cask visual-studio-code
cask webex
cask zoom

tap rcmdnk/file
brew brew-file

tap sidneys/homebrew

tap tlk/imagemagick-x11

# Other Homebrew packages
brew szip

# Other Cask applications
cask mapture

# App Store applications
appstore 892162982   7Zipブラウザ               (2.5.0)
appstore 460883588   ATOK Pad               (2.0.7)
appstore 845313878   EasyAudioRecorderLite  (1.9.1)
appstore 503039729   Fotor Photo Editor     (4.3.9)
appstore 682658836   GarageBand             (10.4.6)
appstore 1462114288  Grammarly for Safari   (9.58)
appstore 408981434   iMovie                 (10.3.3)
appstore 409183694   Keynote                (12.1)
appstore 539883307   LINE                   (7.9.0)
appstore 530194517   MachineProfile         (1.4.13)
appstore 1282504627  Mimeo Photos           (5.0.4)
appstore 409203825   Numbers                (12.1)
appstore 409201541   Pages                  (12.1)
appstore 747648890   Telegram               (8.8)
appstore 497799835   Xcode                  (13.4.1)
